site:
  about:
    siteName: MultiArray
    siteDescription: Multidimensional array for Kotlin.

Editorial:
  primaryColor: '#DE9149'
  social:
    github: 'Lipen/MultiArray'
  menu:
    - type: 'separator'
      title: 'Wiki'
    - type: 'wiki'
    - type: 'separator'
      title: 'API Docs'
    - type: 'kotlindocPackages'
    - type: 'kotlindocClasses'

kotlindoc:
  sourceDirs:
    - './../../main/kotlin'
  pages:
    extraCss:
      - 'assets/css/orchidKotlindoc.scss'
    menu:
      - type: 'kotlindocClassLinks'
        includeItems: true

services:
  publications:
    stages:
      ghPages:
        branch: gh-pages
        username: 'Lipen'
        repo: 'MultiArray'
